### ISSUE TITLE
Lower API level to 24

### ISSUE THREAD

**Issue by Stypox** [kamir86/MycroftDeepspeechCompanionApp#1]
I took a look at the code and it seems like the API level could be lowered to 24 by converting some file accessing code. Currently `java.nio.file.Files` is used, but it is only available on API 26+, so probably `MediaStore` or `SAF` could be used.

**Comment by kamir86** [comment]
that part will be revised when English support is added. 
We can't store all the model on apk so a download procedure is needed in the near future.
Let me know if you need this for the italian model only, removing Files api is a simple task
