### ISSUE TITLE
Crash when tapping on the microphone

### ISSUE THREAD

**Issue by Stypox** [kamir86/MycroftDeepspeechCompanionApp#3]
I built the app on the `master` branch and when I run it in an Android 11 emulator I always get the following crash from logcat:
```
E/AndroidRuntime: FATAL EXCEPTION: STT Thread
    Process: it.awt.mycroft.deepspeech, PID: 4621
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.mozilla.deepspeech.libdeepspeech.DeepSpeechModel.finishStream(org.mozilla.deepspeech.libdeepspeech.DeepSpeechStreamingState)' on a null object reference
        at com.mozilla.speechlibrary.stt.STTLocalClient.decode(STTLocalClient.java:134)
        at com.mozilla.speechlibrary.stt.STTLocalClient.run(STTLocalClient.java:172)
        at java.lang.Thread.run(Thread.java:923)
```

This seems like a deepspeech internal NPE, I don't know if it could be fixed.
Btw, I also tried to run the app from #2 on a real device with Android 7.0, but I get the same error

**Comment by kamir86** [comment]
hello, has this log line been printed? Seems that the model wasn't built.
https://github.com/mozilla/androidspeech/blob/ee3055678bb964a5a3152f5661deb8fb94f4552d/mozillaspeechlibrary/src/main/java/com/mozilla/speechlibrary/stt/STTLocalClient.java#L78
